services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sol-ms-auth-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sol_ms_auth
      DB_USER: changeme
      DB_PASSWORD: changeme
    depends_on:
      - postgres

  postgres:
    image: postgres:18.0
    container_name: sol-ms-auth-postgres
    restart: always
    environment:
      POSTGRES_DB: sol_ms_auth
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
