import typia from "typia";

export interface EmailAuthRequest {
  identifier: string & typia.tags.Format<"email">;
  params: {
    code: string & typia.tags.Pattern<"^[0-9]{6}$">;
  };
}

export interface PasswordAuthRequest {
  identifier: string & typia.tags.Format<"email">;
  params: {
    password: string & 
      typia.tags.MinLength<8> & 
      typia.tags.MaxLength<128> &
      typia.tags.Pattern<"^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d@$!%*?&]{8,}$">;
  };
}

export interface EmailSendRequest {
  identifier: string & typia.tags.Format<"email">;
}

export interface AuthResponse {
  token: string;
}

export interface ErrorResponse {
  error: string;
  message?: string;
}

// Validation functions generated by Typia
export const validateEmailAuth = typia.createValidate<EmailAuthRequest>();
export const validatePasswordAuth = typia.createValidate<PasswordAuthRequest>();
export const validateEmailSend = typia.createValidate<EmailSendRequest>();

// Assert functions for stricter validation
export const assertEmailAuth = typia.createAssert<EmailAuthRequest>();
export const assertPasswordAuth = typia.createAssert<PasswordAuthRequest>();
export const assertEmailSend = typia.createAssert<EmailSendRequest>();
